#define DEV_MODE 0

#define START_LEVEL 1

#define START_CHAR 1

#define START_BUGGY 1

#define START_MUSIC 1

#define PHYSICS_STEP_SIMULATION 2.0f

#define PHYSICS_GRAVITY -3.9f

#define PHYSICS_BACKGROUND_UPDATE
//#define PHYSICS_SINGLETHREAD_UPDATE

#define ENABLE_EDIT_MODE false


//#define SHOW_PAUSE_CONTINUE
//#define RENDER_MIKEY
//#define RENDER_BUGGY
#define RENDER_CAR
