#define MAX_POINT_LIGHTS 200

#define MAX_SPOT_LIGHTS 10

#define MAX_SPOT_SHADOWS 10

//88#define MAX_SPOT_LIGHTS 10
#define MAX_POINT_SHADOWS 5

#define MAX_BONES 200

#define POINT_LIGHT_RADIUS 80.0f
#define SPOT_LIGHT_RADIUS 260.0f

#define LIGHT_SPOT_MULTIPLIER 4.0f
#define LIGHT_POINT_MULTIPLIER 2.0f

#define MAX_VIEW_DISTANCE 100.0f
#define MAX_LIGHT_DISTANCE 100.0f

#define MAX_SFX_DISTANCE 60.0f

#define LIGHT_SHADING_ENABLE

#define GLOW_MIPS 4
#define GLOW_SCALE 8 // th
#define GLOW_BLUR_PASS 4

#define SKY_SIZE 1500.0f
