#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainPanel;
                ref class Grid;
                ref class TextBlock;
                ref class Slider;
                ref class StackPanel;
                ref class ListView;
                ref class AppBarButton;
                ref class ProgressRing;
                ref class Border;
                ref class ComboBox;
                ref class ToggleSwitch;
                ref class AppBar;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualStateGroup;
            ref class VisualState;
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                namespace Primitives {
                    ref class Popup;
                }
            }
        }
    }
}

namespace Game
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class DirectXPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class DirectXPage_obj26_Bindings;
        class DirectXPage_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::SwapChainPanel^ DXSwapChainPanel;
        private: ::Windows::UI::Xaml::VisualStateGroup^ GameInfoOverlayStates;
        private: ::Windows::UI::Xaml::VisualState^ NormalState;
        private: ::Windows::UI::Xaml::VisualState^ GameInfoOverlayState;
        private: ::Windows::UI::Xaml::VisualState^ TooSmallState;
        private: ::Windows::UI::Xaml::VisualState^ NotTooSmallState;
        private: ::Windows::UI::Xaml::Controls::Grid^ GamePlayInfo;
        private: ::Windows::UI::Xaml::Controls::Grid^ TooSmallView;
        private: ::Windows::UI::Xaml::Controls::Grid^ GameInfoOverlay;
        private: ::Windows::UI::Xaml::Controls::Primitives::Popup^ StoreFlyout;
        private: ::Windows::UI::Xaml::Controls::Grid^ GameOptions;
        private: ::Windows::UI::Xaml::Controls::Grid^ GameMenu;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ option1b;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ option1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ option12;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ option2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ option3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ option1b2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ option32;
        private: ::Windows::UI::Xaml::Controls::Slider^ draw_distance;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ fxaa_value;
        private: ::Windows::UI::Xaml::Controls::Grid^ StoreGrid;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ StoreUnavailable;
        private: ::Windows::UI::Xaml::Controls::ListView^ ProductListView;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ Return;
        private: ::Windows::UI::Xaml::Controls::Grid^ Loading;
        private: ::Windows::UI::Xaml::Controls::Grid^ Stats;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ PleaseWait;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ PlayAgain;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ HighScoreTitle;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ HighScoreData;
        private: ::Windows::UI::Xaml::Controls::Grid^ PurchaseUpgrade;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ BuyFull;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ PurchaseMessage;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ HighScore;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TotalShots;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TotalPoints;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LevelsCompleted;
        private: ::Windows::UI::Xaml::Controls::ProgressRing^ LoadingProgress;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ GameInfoOverlayTitle;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ BonusTimeTitle;
        private: ::Windows::UI::Xaml::Controls::Grid^ right_cols;
        private: ::Windows::UI::Xaml::Controls::Slider^ sambr;
        private: ::Windows::UI::Xaml::Controls::Slider^ sambg;
        private: ::Windows::UI::Xaml::Controls::Slider^ sambb;
        private: ::Windows::UI::Xaml::Controls::Slider^ sdiffr;
        private: ::Windows::UI::Xaml::Controls::Slider^ sdiffg;
        private: ::Windows::UI::Xaml::Controls::Slider^ sdiffb;
        private: ::Windows::UI::Xaml::Controls::Slider^ sambsky;
        private: ::Windows::UI::Xaml::Controls::Slider^ sdiffsky;
        private: ::Windows::UI::Xaml::Controls::Slider^ sskybright;
        private: ::Windows::UI::Xaml::Controls::Slider^ sdiffx;
        private: ::Windows::UI::Xaml::Controls::Slider^ sdiffy;
        private: ::Windows::UI::Xaml::Controls::Slider^ sdiffz;
        private: ::Windows::UI::Xaml::Controls::Slider^ sspecr;
        private: ::Windows::UI::Xaml::Controls::Slider^ sspecg;
        private: ::Windows::UI::Xaml::Controls::Slider^ sspecb;
        private: ::Windows::UI::Xaml::Controls::Slider^ sspecpow;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ slider_controls;
        private: ::Windows::UI::Xaml::Controls::Grid^ PauseData;
        private: ::Windows::UI::Xaml::Controls::Grid^ LevelStart;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ BonusTimeData;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ BonusTime;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TimeLimit;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Objective;
        private: ::Windows::UI::Xaml::Controls::Slider^ sliderrr;
        private: ::Windows::UI::Xaml::Controls::Slider^ sliderrg;
        private: ::Windows::UI::Xaml::Controls::Slider^ sliderrb;
        private: ::Windows::UI::Xaml::Controls::Border^ col_view;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ combo1;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ TapToContinue;
        private: ::Windows::UI::Xaml::Controls::Slider^ deleteradius;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ b_edasplay;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ b_fly;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ b_fog;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ b_rain;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ b_snow;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ combo2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat6;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat7;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat8;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat9;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat10;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat11;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat12;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat13;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat14;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat15;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat16;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat17;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dat18;
        private: ::Windows::UI::Xaml::Controls::AppBar^ GameAppBar;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ Play;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ NextLev;
    };
}

